name: CI-guard

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-scan:
    name: Run CI-guard
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Terraform Init
      run: terraform init

    - name: Run Security Scanner
      run: |
        cd scanner
        python security_scanner.py --tf-dir=..

    - name: Upload debug files (if any)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: debug-files
        path: |
          debug_plan.json